import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Breadcrumb from "@/components/Breadcrumb";
import Footer from "@/components/navbar/Footer";
import UpperNavbar from "@/components/navbar/UpperNavbar";
import Navbar from "@/components/navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UpperNavbar />
        <Navbar />
        <main className="flex-1 ">
          <Breadcrumb />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
